# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates



# Gromit-MPX - herramienta de anotación en pantalla
windowrule {
    name = Gromit-MPX
    match:class = ^(Gromit-mpx)$
    no_blur = on
    no_shadow = on
    opacity = 1.0 override 1.0 override
    no_anim = on
}
